on:
  push

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Get repo
        uses: actions/checkout@v4
        
      - name: Deploy
        env: 
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_ACCOUNT_ID: ${{ secrets.DATABRICKS_ACCOUNT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
        run: |
          pwd
          ls -l
          databricks auth login
          databricks bundle deploy
          databricks bundle run db
